# Generated by Django 5.2 on 2025-05-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_listings_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='active',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
