# Generated by Django 5.2 on 2025-05-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_listings_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
