# Generated by Django 5.2 on 2025-05-05 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_category_rename_bids_bid_rename_comments_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
