# Generated by Django 5.2 on 2025-05-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_photos_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='img',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
